[
tool.poetry
]
name = "ip-information-checker"
version = "1.0.0"

[
tool.poetry.dependencies
]
python = "^3.9"
aiohttp = "^3.8.1"
requests = "^2.27.1"
tenacity = "^8.0.1"
ipaddress = "^1.0.23"
json = "^2.0.9"
os = "^0.1.1"
sys = "^0.1.1"
time = "^0.1.1"
logging = "^0.5.1.2"
argparse = "^1.4.0"

[
tool.poetry.dev-dependencies
]
pytest = "^6.2.5"

[
build-system
]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"